// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1) {
  return window['go']['api']['App']['AddModel'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['api']['App']['CheckForUpdates'](arg1);
}

export function CheckProvider(arg1, arg2) {
  return window['go']['api']['App']['CheckProvider'](arg1, arg2);
}

export function ClearDB() {
  return window['go']['api']['App']['ClearDB']();
}

export function DetectGPU() {
  return window['go']['api']['App']['DetectGPU']();
}

export function DownloadLLama(arg1) {
  return window['go']['api']['App']['DownloadLLama'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['api']['App']['DownloadUpdate'](arg1);
}

export function GetConfig() {
  return window['go']['api']['App']['GetConfig']();
}

export function GetCtx() {
  return window['go']['api']['App']['GetCtx']();
}

export function GetLLamaStatus() {
  return window['go']['api']['App']['GetLLamaStatus']();
}

export function GetModelInfo(arg1) {
  return window['go']['api']['App']['GetModelInfo'](arg1);
}

export function ImageDataURI(arg1) {
  return window['go']['api']['App']['ImageDataURI'](arg1);
}

export function ListModels() {
  return window['go']['api']['App']['ListModels']();
}

export function ListRemoteModels(arg1, arg2) {
  return window['go']['api']['App']['ListRemoteModels'](arg1, arg2);
}

export function PickFolder() {
  return window['go']['api']['App']['PickFolder']();
}

export function ProviderPresets() {
  return window['go']['api']['App']['ProviderPresets']();
}

export function RecentSearches() {
  return window['go']['api']['App']['RecentSearches']();
}

export function RemoveModel(arg1) {
  return window['go']['api']['App']['RemoveModel'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['api']['App']['RevealInExplorer'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['api']['App']['SaveSettings'](arg1);
}

export function ScanFolder(arg1, arg2) {
  return window['go']['api']['App']['ScanFolder'](arg1, arg2);
}

export function Search(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['App']['Search'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectGGUFFile() {
  return window['go']['api']['App']['SelectGGUFFile']();
}

export function SetActiveModel(arg1) {
  return window['go']['api']['App']['SetActiveModel'](arg1);
}

export function SetLocalAutoStart(arg1) {
  return window['go']['api']['App']['SetLocalAutoStart'](arg1);
}

export function SetLocalModel(arg1, arg2) {
  return window['go']['api']['App']['SetLocalModel'](arg1, arg2);
}

export function StopLLamaServer() {
  return window['go']['api']['App']['StopLLamaServer']();
}
