// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function AddModel(arg1:api.AddModelConfig):Promise<api.ModelInfo>;

export function CheckForUpdates(arg1:boolean):Promise<api.UpdateInfo>;

export function CheckProvider(arg1:string,arg2:string):Promise<Array<api.RemoteModel>>;

export function ClearDB():Promise<void>;

export function DetectGPU():Promise<api.GPUInfoResult>;

export function DownloadLLama(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:api.UpdateInfo):Promise<void>;

export function GetConfig():Promise<api.appConfig>;

export function GetCtx():Promise<context.Context>;

export function GetLLamaStatus():Promise<api.LLamaStatus>;

export function GetModelInfo(arg1:string):Promise<api.ModelInfo>;

export function ListModels():Promise<Array<api.ModelInfo>>;

export function ListRemoteModels(arg1:string,arg2:string):Promise<Array<api.RemoteModel>>;

export function PickFolder():Promise<string>;

export function ProviderPresets():Promise<Array<api.ProviderPreset>>;

export function RecentSearches():Promise<Array<string>>;

export function RemoveModel(arg1:string):Promise<void>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveSettings(arg1:api.SaveSettingsReq):Promise<void>;

export function ScanFolder(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<Array<api.SearchHit>>;

export function SelectGGUFFile():Promise<string>;

export function SetActiveModel(arg1:string):Promise<void>;

export function SetLocalAutoStart(arg1:boolean):Promise<void>;

export function SetLocalModel(arg1:string,arg2:number):Promise<void>;

export function StopLLamaServer():Promise<void>;
